### ISSUE TITLE
ERROR when using allowMultiSelect together with <input />

### ISSUE THREAD

**Issue by AndreiLukashevich** [vlio20/angular-datepicker#165] opened 2017-08-09 12:14 UTC
I use datepicker with <input />. 

Template:
<input id=date" formControlName="date" class="form-control" [(ngModel)]="date" [dpDayPicker]="config"  theme="dp-material"  mode="day" />

Component:
config: IDatePickerConfig = {
    allowMultiSelect: true,
    format: "MM/DD/YYYY"
  };

If I use the value  allowMultiSelect: false, then there is no error.
If I use the value allowMultiSelect: true, an error occurs in the console:

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: ''.
    at viewDebugError (core.es5.js:8420)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8398)
    at checkBindingNoChanges (core.es5.js:8562)
    at checkNoChangesNodeInline (core.es5.js:12425)
    at checkNoChangesNode (core.es5.js:12397)
    at debugCheckNoChangesNode (core.es5.js:13174)
    at debugCheckDirectivesFn (core.es5.js:13076)
    at Object.eval [as updateDirectives] (DateTimePickerComponent.html:11)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13058)
    at checkNoChangesView (core.es5.js:12217)
View_DateTimePickerComponent_0 @ DateTimePickerComponent.html:11
proxyClass @ compiler.es5.js:14971
DebugContext_.logError @ core.es5.js:13398
ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:4814
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:141
NgZone.runOutsideAngular @ core.es5.js:3844
ApplicationRef_.tick @ core.es5.js:4814
(anonymous) @ core.es5.js:4684
ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:3890
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:141
NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
ZoneDelegate.hasTask @ zone.js:444
ZoneDelegate._updateTaskCount @ zone.js:464
Zone._updateTaskCount @ zone.js:288
Zone.runTask @ zone.js:208
drainMicroTaskQueue @ zone.js:595
ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1370
globalZoneAwareCallback @ zone.js:1388
DateTimePickerComponent.html:11
 
ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 21, nodeDef: {…}, elDef: {…}, elView: {…}}

**Comment by vlio20** [comment] 2017-08-09 13:01
on what version are you?

**Comment by AndreiLukashevich** [comment] 2017-08-09 13:31
angular 4 (4.3.3), (@angular/cli@1.0.3)

**Comment by vlio20** [comment] 2017-08-09 13:46
I am talking about three version of this component.

**Comment by AndreiLukashevich** [comment] 2017-08-09 16:01
I use derective
Directive

You can use the [dpDayPicker] directive to attach the picker to any component with an ngModel or a FormControl (using reactive forms).

i.e.

<input name="someName" [(ngModel)]="selectedDate" [dpDayPicker]="config" />

**Comment by AndreiLukashevich** [comment] 2017-08-09 16:02
and I use reactive form
<input name="someName" formControlName="selectedDate" [dpDayPicker]="config" />

**Comment by vlio20** [comment] 2017-08-09 16:13
Still, what npm version of this component are you using?

**Comment by AndreiLukashevich** [comment] 2017-08-09 16:41
ng2-date-picker@2.3.1

**Comment by vlio20** [comment] 2017-08-09 17:02
Does it happens also in the demo?

**Comment by AndreiLukashevich** [comment] 2017-08-09 17:09
If I add in the demo in the config  allowMultiSelect: true, then in the demo the error is also present.

**Comment by vlio20** [comment] 2017-08-09 19:02
@AndreiLukashevich. I would happy to help you but it seems that I can't reproduce the issue. It would be very helpful if you will post a very simple demo with your implementation.

**Comment by AndreiLukashevich** [comment] 2017-08-10 08:53
I created the demo project. When I go to the DatePicker component , an error appears in the browser console.

https://github.com/AndreiLukashevich/angular-datepicker-demo

**Comment by vlio20** [comment] 2017-08-10 09:23
Awesome! I will take a look asap

**Comment by vlio20** [comment] 2017-08-11 19:30
Issue was fixed on master, will be available in next version (2.3.2)

**Closed by vlio20** 2017-08-11 19:30 UTC
