### ISSUE TITLE
[BUG] calendar doesn't close consistently on close

### ISSUE THREAD

**Issue by WaterBleu** [vlio20/angular-datepicker#200] opened 2017-09-20 20:58 UTC
symptom: when multiple input exists calendar doesn't close consistently

[updated plunker](http://plnkr.co/edit/MyNzic?p=preview) <~ can also be used for future ng2-date-picker template

**Comment by vlio20** [comment] 2017-09-21 04:53
What are the steps to reproduce

**Comment by WaterBleu** [comment] 2017-09-21 16:46
steps are putting 2 md-input onto the screen and attach datepicker to both

**Comment by vlio20** [comment] 2017-09-21 17:11
And what happens then?

**Comment by WaterBleu** [comment] 2017-09-21 17:13
when clicking on the calendar it doesn't close consistently

**Comment by vlio20** [comment] 2017-09-21 18:48
@WaterBleu, I will need your help with that one. Could you please create a fork and than create a demo which reproduces the issue as seen in the plunker you provided?

**Comment by WaterBleu** [comment] 2017-09-22 16:35
what do you mean exactly by create a fork and create demo? cause the demo is in plunker no?

**Comment by vlio20** [comment] 2017-09-22 16:41
the demo on plunker is using the component, I would like to be able to access the component code, so it would be much more convenient to have it set in the demo page of this component - you will find a demo component in the src of this project.

**Comment by vlio20** [comment] 2017-09-30 15:42
closing for now

**Comment by marcelcpx** [comment] 2018-03-28 10:02
I created a [fork](https://github.com/marcelcpx/angular-datepicker/tree/bug/not-closing) and added a second date picker to the demo page. The first time you open one of the date pickers you cannot close it immediately by clicking outside of it, you can even open two date pickers at the same time. After closing one of the date pickers the first time, the behaviour is as expected.

When creating even more date pickers on a page, you must click outside the box twice the first time for every date picker you add.

**Comment by marcelcpx** [comment] 2018-04-03 11:23
@vlio20 BTW, the [Stackblitz](https://stackblitz.com/edit/ng-datepicker-test) provided in a recent [issue](https://github.com/vlio20/angular-datepicker/issues/384) exhibits the same bug.

**Comment by marcelcpx** [comment] 2018-04-03 11:27
Tested a bit further, Chrome and Edge don't seem to be affected, so far only Firefox is erratic.

**Comment by vlio20** [comment] 2018-04-03 11:29
Hate this browser specific bugs. So FF only?

**Comment by marcelcpx** [comment] 2018-04-03 11:31
I don't have Opera here, but Edge, IE 11, Safari for Windows and Chromium are not affected. Indeed, FF only (running 59.0.2 on Windows 10, here).

**Comment by sunnykantkr** [comment] 2018-07-10 07:42
> Apologies, this is my first comment on GitHub. I am not sure I am understanding the issue right. I was having the same problem where I have two `input`, each having angular-datepicker binded to it. I have used Directive feature and also using Material design. After selecting date, the  date from the date picker is populated on the input textbox but the picker is not closed and a flick effect happens like it closed and opened again.

#87 

> @WaterBleu Please refer issue: [87](https://github.com/vlio20/angular-datepicker/issues/87) which solved my problem.

> In this @vlio20  stated : seems like the md-input-container is listening to clicks on it child elements and this is what causes the "re-focusing". As a workaround I would suggest you to use `appendTo: body` in the config object you pass to the component.

**Comment by marcelcpx** [comment] 2018-07-10 12:51
This only partially solves the issue: if I put multiple datepickers in one component, I still cannot close a datepicker using a click outside of the field the first time.

**Comment by vlio20** [comment] 2018-07-22 20:38
isn't it a duplicate of 377?

**Comment by marcelcpx** [comment] 2018-07-31 14:09
I'm now away from work, so I can't test it thoroughly. I'll come back at this issue somewhere next week.

Thanks anyway!

**Comment by vlio20** [comment] 2019-12-20 11:45
This issue is not reproduced anymore. closing.

**Closed by vlio20** 2019-12-20 11:45 UTC
Labels: Investigation, help wanted
