### ISSUE TITLE
Not Setting dpDayPicker to Dirty when using  the mouse to Select another Date

### ISSUE THREAD

**Issue by whoang11** [vlio20/angular-datepicker#121] opened 2017-07-07 01:52 UTC
I upgraded to the version 2.1.1. This version has fixed the issue of setting the dpDayPicker to dirty initially. However, this version has a new problem of not setting the dpDayPicker to dirty when I used the mouse to select another date.

If I typed in another date, the dpDayPicker was correctly set to dirty.

For this new problem, I went back to version 1.4.3 and continued using this work around solution:
setTimeout(() => {
this.appointmentForm.get('appointmentDate').markAsPristine(true);
}, 10);

Thanks,

**Comment by vlio20** [comment] 2017-07-12 07:15
I will check this one as soon as I will have time. I think I know already the reason. Thanks!

**Comment by vlio20** [comment] 2017-07-19 20:24
@whoang11, Angular question: what should be the form state be if you initialise the form with date (on startup) should it be dirty?

**Comment by whoang11** [comment] 2017-07-20 12:14
The form state should be dirty after initializing a default date on start up. If you do not set a default date during start up, the form state should be pristine or not dirty. 
Looks like you have fixed this issue. I will use your latest version of the dpDayPicker and let you know the result.
Thanks, 

    On Thursday, July 20, 2017 1:20 AM, Vlad Ioffe <notifications@github.com> wrote:
 

 Closed #121 via 7cf54df.—

**Comment by vlio20** [comment] 2017-07-20 12:33
Thanks!

**Comment by whoang11** [comment] 2017-07-20 13:07
I used NPM to get your latest version, 2.1.1. Initially, the dpDayPicker column was blank. If I used the mouse to select a new date, this column was not changed to dirty. If I typed in the new date, this column was correctly set to dirty. The dpDaypicker column should have been changed to dirty whether I used the mouse or keyboards to change the date.
Therefore, I will go back to the old version and continue using my work around solution. I suggest that this issue should have not been closed. Do you still plan or have time to fix this issue? 
Thanks, 

    On Thursday, July 20, 2017 7:33 AM, Vlad Ioffe <notifications@github.com> wrote:
 

 Thanks!—

**Comment by vlio20** [comment] 2017-07-20 13:36
@whoang11, the fixed is not released yet, it's only on master. Are you using master?

**Comment by vlio20** [comment] 2017-07-25 06:44
fixed in 2.2.0. @whoang11 can you verify?

**Comment by whoang11** [comment] 2017-07-25 15:06
Unfortunately, Version 2.2.0 has NOT  fixed this same issue: 

 Initially, the dpDayPicker column was blank. If I used the mouse to select a new date, this column was not changed to dirty. If I typed in the new date, this column was correctly set to dirty. The dpDaypicker column should have been changed to dirty whether I used the mouse or keyboards to change the date.

I am using Angular 4.3.0, Angular/cli 1.2.1, Typscript 2.4.1. Would you code work with these versions?

**Comment by vlio20** [comment] 2017-07-25 15:08
Can you please break it to steps? I probably missing something

**Comment by whoang11** [comment] 2017-07-25 15:12
Could you elaborate the meaning of breaking it to steps?

**Comment by vlio20** [comment] 2017-07-25 15:13
1. Go to... 
2. Press.. 
....

**Comment by whoang11** [comment] 2017-07-25 15:30
Using the mouse to select a date.
1. I opened the screen that has the dpDayPicker column with no date on it.
2. I used the mouse to select a date on the dpDayPicker column and exit this screen by navigating to another screen.
3. Since the dpDayPicker was not changed to dirty, I did not get confirmation screen asking me to exit the screen.

Use the keyboard to type in a date
1. I opened the screen that has the dpDayPicker column with no date on it.
2. I used the keyboard to type a date on the dpDayPicker column and exited this screen by navigating to another screen.
3. This time, the dpDayPicker column was changed to dirty, and  I got a confirmation screen asking me to exit the screen.

If I used the older version with my work around solution, the date field was changed to dirty with mouse and keyboard

**Comment by vlio20** [comment] 2017-07-26 12:27
@whoang11, can you please post a demo repo, I couldn't reproduce this issue. I added `{{form.form.dirty}} ` next to the form in the demo and it seems like the form is updated correctly both after mouse click or keyboard change.

**Comment by whoang11** [comment] 2017-07-27 20:46
I will create a demo project that has the DpDayPicker field and post it on GitHub this weekend.

**Comment by vlio20** [comment] 2017-07-27 20:50
That would be awesome!!

**Comment by whoang11** [comment] 2017-07-30 23:12
Here is the link for project that you can check out the issue with pristine status on DpDayPicker column using Reactive form:
https://github.com/whoang11/DatePickerDemo

Below is my test of this datepicker column:
![dpdaypickertestpristine](https://user-images.githubusercontent.com/7757548/28757897-77e979b0-7552-11e7-9f81-e20424102232.PNG)

Thanks,

**Comment by vlio20** [comment] 2017-07-31 05:56
Awesome will take a look ASAP!

**Comment by vlio20** [comment] 2017-07-31 18:31
@whoang11, can you please check if master version fixes the issue for you?

**Comment by whoang11** [comment] 2017-08-01 15:08
I copied my code into the demo.component (.ts, .html, and .less) of your master version.  I used the mouse to select a date, and it correctly changed the  DpDayPicker's pristine to false. Here is the screen shot of the test:
![dpdaypickerok](https://user-images.githubusercontent.com/7757548/28831812-58555b7e-76a0-11e7-85d4-e465256705a2.PNG)

When do you plan to release this latest version to NPM?

Thanks,

**Comment by vlio20** [comment] 2017-08-01 17:20
I hope in the next few days

**Closed** 2017-08-04 07:45 UTC
Labels: bug
