### ISSUE TITLE
dp-time-select ngModel behavior

### ISSUE THREAD

**Issue by anleodev** [vlio20/angular-datepicker#459] opened 2019-08-29 12:54 UTC
Hello,
We are experiencing a problem with ngModel behaviour of dp-time-select component, the point is if the value updated somewhere outside of component - it's changed back to it's previous value, which is set inside of component. Shouldn't it be vice versa? And if no - how can we update the value inside of the component after it's initialisation, if we have a case, where we need it?

Angular version: 7.2.5
Package Version: 2.12.0(was also checking on 2.8)
Browser specific: false

![image](https://user-images.githubusercontent.com/50413217/63941439-543fdf80-ca74-11e9-9f0a-d0917fcaaebd.png)

**Comment by vlio20** [comment] 2019-08-29 13:34
The component should react to changes in the value. Make sure that the object that is passed to it is being changed. If it still doesn't work properly then please post a stackblitz in which I could reproduce the issue

**Comment by anleodev** [comment] 2019-08-29 14:23
Well, the component doesn't react to changes after initialisation, because in ngOnChanges(triggered by changing model) you call this.init() which
resets the current value by

this.selected = this.selected || moment();

**Comment by anleodev** [comment] 2019-08-29 14:34
Well, the component's doesn't reaction to changes is blocked, if changing model also calls ngOnChanges lifecycle, there you call this.init()

which makes 
this.selected = this.selected || moment();

and this is returning component to old value, dropping the model change.

**Comment by anleodev** [comment] 2019-08-29 15:11
Created a pull request for that.
I'd be very thankful if you will apply and deploy it with new version someday.

**Comment by vlio20** [comment] 2019-12-16 21:20
@anleodev sorry for checking this so late.

I am unable to reproduce
I am not sure what do you mean when you say:

> the value updated somewhere outside of component - it's changed back to it's previous value

If you could provide a stackblitz it would help a lot.

**Comment by vlio20** [comment] 2019-12-20 11:40
closing for now

**Closed by vlio20** 2019-12-20 11:40 UTC
Labels: more info needed
