### ISSUE TITLE
AllowmultipleSelect not returning Selected Dates As an Array

### ISSUE THREAD

**Issue by avineet1993** [vlio20/angular-datepicker#396] opened 2018-04-30 11:56 UTC
HTML : 
<dp-date-picker id="datePicker"
                        name="datePicker"
                        #dateComponent
                        #datePickerModel="ngModel"
                        [(ngModel)]="holidaydates"
                        [mode]="'day'"
                        [displayDate]="displayDate"
                        [placeholder]="placeholder"
                        [config]="config"
                        [theme]="material ? 'dp-material dp-main' : 'dp-main'"
                        (onSelect)="onSelect($event)"
                        (ngModelChange)=addNewDate($event.target.value)>
        </dp-date-picker>

TypeScript:

 holidaydates: Moment[] = [];
    config: IDatePickerConfig = {
    firstDayOfWeek: 'su',
    monthFormat: 'MMM, YYYY',
    disableKeypress: false,
    allowMultiSelect: true,
    closeOnSelect: undefined,
    closeOnSelectDelay: 100,
    openOnFocus: true,
    openOnClick: true,
    onOpenDelay: 0,
    weekDayFormat: 'ddd',
    appendTo: document.body,
    showNearMonthDays:   true,
    showWeekNumbers: false,
    enableMonthSelector: true,
    yearFormat: 'YYYY',
    showGoToCurrent: true,
    dayBtnFormat: 'DD',
    monthBtnFormat: 'MMM',
    multipleYearsNavigateBy: 10,
    showMultipleYearsNavigation: false,
    returnedValueType: 2,
    unSelectOnClick: true,
    hideOnOutsideClick: true
  }

Data is not binding to the model .
@vlio20

**Comment by avineet1993** [comment] 2018-05-01 01:12
https://stackblitz.com/edit/angular-ztltpd

how to separate multiple  date by comma instead of delimiter?

**Comment by vlio20** [comment] 2018-07-22 20:39
I will take a look ASAP though there are some other things on the pipeline. If it's really urgent, consider reach via [Fiverr](https://www.fiverr.com/vladioffe/add-features-and-fix-bugs?arrived_from_manage_gigs=true&display_share=true).

**Comment by vlio20** [comment] 2018-10-23 17:21
@avineet1993 , is this still happening?

**Comment by abhilashmaipady** [comment] 2019-12-04 13:05
@vlio20 This issue is still persist. Not able to bind Array of Moment Obj into model.
![image](https://user-images.githubusercontent.com/15060415/70144824-c273ee00-16c4-11ea-91e4-962e975501db.png)

**Comment by vlio20** [comment] 2019-12-20 11:39
@abhilashmaipady I am unable to reproduce, the stackbliz you posted is working.
Please provide steps to reproduce and update the stackblitz.

**Comment by abhilashmaipady** [comment] 2019-12-21 19:38
> @abhilashmaipady I am unable to reproduce, the stackbliz you posted is working.
> Please provide steps to reproduce and update the stackblitz.

I am also not able to reproduce this issue in my local or stackblitz project. I had this issue in production code. Now I am using date-picker directive instead of date-picker component.

**Comment by vlio20** [comment] 2019-12-21 19:55
cool, so I will close this for now

**Closed by vlio20** 2019-12-21 19:55 UTC
Labels: more info needed
