### ISSUE TITLE
Error when use with formControlName

### ISSUE THREAD

**Issue by jamalx31** [vlio20/angular-datepicker#128] opened 2017-07-13 13:00 UTC
When using the component with [formControlName]="prop.id" inside a form I get the error 
`v.format is not a function`

version: 2.1.1

angular/cli: 1.2.0
node: 7.7.3
os: darwin x64
angular/animations: 4.2.6
angular/cdk: 2.0.0-beta.8
angular/cli: 1.2.0
angular/common: 4.2.6
angular/compiler: 4.2.6
angular/compiler-cli: 4.2.6
angular/core: 4.2.6
angular/flex-layout: 2.0.0-beta.7
angular/forms: 4.2.6
angular/http: 4.2.6
angular/material: 2.0.0-beta.8
angular/platform-browser: 4.2.6
angular/platform-browser-dynamic: 4.2.6
angular/platform-server: 4.2.6
angular/router: 4.2.6
angular/language-service: 4.2.6

**Comment by vlio20** [comment] 2017-07-13 13:02
Can you please post a demo repo?

**Comment by jamalx31** [comment] 2017-07-13 14:38
@vlio20 https://github.com/jamalx31/angular-datepicker
`npm start`

I just figured out that adding the 'disabled' property to the control is what cause the issue
`new FormControl({ disabled: false })`

**Comment by vlio20** [comment] 2017-07-13 18:03
I am not sure what exactly `new FormControl({ disabled: false })` is for, can you please elaborate?

**Comment by jamalx31** [comment] 2017-07-14 11:53
@vlio20 when you put an element inside a form you can use name="blabal" or if you wanna define a customized control you use  [formControlName]="blabla"

```
Syncs a FormControl in an existing FormGroup to a form control element by name.
In other words, this directive ensures that any values written to the FormControl instance programmatically will be written to the DOM element (model -> view). Conversely, any values written to the DOM element through user input will be reflected in the FormControl instance (view -> model).
```

In my case define to control with `new FormControl({ disabled: false })`

**Comment by vlio20** [comment] 2017-07-14 18:38
I will take a look ASAP. Thanks!

**Comment by vlio20** [comment] 2017-07-14 21:54
@jamalx31, why are you passing `{ disabled: false }`? If you want to disable the input filed just add an attribute for that:  
```
<dp-date-picker [disabled]="disabled" [formControlName]="'startDate'" [(ngModel)]="startDate" type="day" [theme]="'dp-material'"></dp-date-picker>
```

**Comment by vlio20** [comment] 2017-07-14 22:09
I found the issue, with reactive forms you can pass the disabled option within the `FormGroup` the problem is (I think) that it is not valid for this component to be used this way. If you want to use the disabled option you will have to use it with plain template:  
```
<dp-date-picker [disabled]="disabled" [formControlName]="'startDate'" [(ngModel)]="startDate" type="day" [theme]="'dp-material'"></dp-date-picker>
```

Not sure how to make the disabled to be working with passing it through the `FormGroup` disabled property. Any suggestions will be much appreciated.

**Comment by vlio20** [comment] 2017-07-14 22:10
Maybe this one will help: 
https://stackoverflow.com/a/40697821/1691423

**Comment by vlio20** [comment] 2017-07-14 22:17
@jamalx31, I found the way to handle the reactive way approach of disabling the component - will be added in my next release. There is another issue (which also will be fixed soon) you will have to provide a null value: 
``` 
  ngOnInit(): void {
    this.form = this.fb.group({
      startDate: new FormControl({disabled: false, value: null})
    });
  }

```

**Comment by jamalx31** [comment] 2017-07-17 11:44
@vlio20 thanks that works
just to note that when [(ngModel]) is used an initial value should be passed to FormControl
doesn't matter what could be just an empty string
`new FormControl({disabled: false, value: ''})`

**Comment by vlio20** [comment] 2017-08-04 08:06
@jamalx31, I am not sure if this issue is already solved. can you give your input pls?

**Comment by vlio20** [comment] 2017-08-11 19:31
will close this for now

**Closed by vlio20** 2017-08-11 19:31 UTC
