### ISSUE TITLE
[BUG] value.split is not a function

### ISSUE THREAD

**Issue by WaterBleu** [vlio20/angular-datepicker#245] opened 2017-10-16 16:52 UTC
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [x] Provide **screenshots** where appropriate
- [x] What's the **version** of Angular you're using? 4.45
- [ ] Does this occur on specific browser?
![error screen](https://user-images.githubusercontent.com/10839706/31624368-58937e02-b257-11e7-87a9-23fb39d24519.png)

I believe the error comes from upgrading the version.
Unfortunately I have no idea what cause this exactly to provide a code snippet

**Comment by WaterBleu** [comment] 2017-10-16 16:58
@vlio20  problem only exist in 2.5 and above, rolled back to 2.4 and was fine

**Comment by vlio20** [comment] 2017-10-16 17:06
Please rovide the component you are using and your configuration

**Comment by WaterBleu** [comment] 2017-10-16 18:59
<input #datePicker [(ngModel)]="selectedDate"  [dpDayPicker]="dtPickerConfigWithoutTime" theme="dp-material" attachTo=".page-date-picker">

dtPickerConfigWithoutTime = {
      format: 'YYYY-MM-DD',
      closeOnSelect: true
};

**Comment by vlio20** [comment] 2017-10-16 21:11
Resolved in 94af6c1. Will be available in 2.6.0.

Thanks for raising the issue.

**Closed by vlio20** 2017-10-16 21:11 UTC
Labels: bug

**Comment by WaterBleu** [comment] 2017-11-03 22:21
@vlio20 problem persists in 2.6.0 and 2.6.1

**Comment by vlio20** [comment] 2017-11-04 06:13
I can't reproduce it... Can you please provide more details
