### ISSUE TITLE
Two Way Binding ngModel

### ISSUE THREAD

**Issue by janbro** [vlio20/angular-datepicker#107] opened 2017-06-21 18:52 UTC
It seems that when I update my variable `date` binded to the datepicker value, it does not change in the input field value on the component. Angular 4.

`<dp-date-picker type="month" [(ngModel)]="date" [config]="datePickerConfig"></dp-date-picker>`

**Comment by vlio20** [comment] 2017-06-22 09:43
will check, thanks.

**Comment by C-F-4** [comment] 2017-06-22 12:18
Checked it out
app.component.html
`<input name="someName" [(ngModel)]="selectedDate" [dpDayPicker]="config" theme="dp-material"/>
<button (click)="foo()">Print</button>`

app.component.ts
```
export class AppComponent {
  private config: IDatePickerConfig = {
    weekdayNames : {
      su: 'S',
      mo: 'M',
      tu: 'T',
      we: 'W',
      th: 'Th',
      fr: 'F',
      sa: 'Sa'
    },
    max: Moment(new Date())
  };

  private selectedDate: string = "11-06-2017";

  constructor() {}
  ngOnInit() {}

  foo():void {
    console.log(this.selectedDate + "\nType: " + typeof(this.selectedDate));
  }
}
```

Does the 2-way binding fine, but with error:
_ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '11-06-2017'. Current value: ''._

**Comment by vlio20** [comment] 2017-06-30 18:55
sorry I couldn't reproduce it on master.
I created a butting which sets the date programmatically. 
Will close it for now, please reopen if it happens for you with demo repo. Thanks!

**Closed by vlio20** 2017-06-30 18:55 UTC
Labels: help wanted
