### ISSUE TITLE
has no exported member 'ValidationErrors'

### ISSUE THREAD

**Issue by chendzng** [vlio20/angular-datepicker#113] opened 2017-06-28 04:42 UTC
![image](https://user-images.githubusercontent.com/22837417/27620863-d4493580-5bf6-11e7-81dc-ea1f00e30d96.png)

**Comment by chendzng** [comment] 2017-06-28 04:42
may i know what caused this ?

**Comment by vlio20** [comment] 2017-06-29 09:13
mmm.. don't know.... 
Can you please upload a demo repo?

**Comment by chendzng** [comment] 2017-06-30 09:21
![image](https://user-images.githubusercontent.com/22837417/27729315-a49c5726-5daf-11e7-81ac-bdb5afce7085.png)
this is from your `day-calendar.component.d.ts`

and i was hoping to have a Active Dates , right now can bind to an `NgModel ` which cause the date selected , or can i achieve something like active dates ? sorry OOT

**Comment by vlio20** [comment] 2017-06-30 18:58
I will have to get a demo in order to reproduce your issue, could you supply one?

**Comment by chendzng** [comment] 2017-06-30 19:07
a new repo just with this package will do ? @vlio20

**Comment by vlio20** [comment] 2017-06-30 19:13
sure, with some very basic usage of the component with your configuration.
By the way I just released new version 2.0.0 - please see if it happens there as well.

**Comment by Leyli698** [comment] 2017-07-12 08:48
I faced the same problem. Could you solve it?

**Comment by vlio20** [comment] 2017-07-12 09:44
@Leyli698,  Can you please post a demo repo?

**Comment by vlio20** [comment] 2017-07-19 19:33
closing for now. will reopen if more info will be provided.

**Closed by vlio20** 2017-07-19 19:33 UTC
Labels: help wanted

**Comment by YasserMuhammad** [comment] 2017-10-01 13:10
i have the same error and i think it's because there's no export for ValidationErrors in @angular/forms

**Comment by vlio20** [comment] 2017-10-01 14:32
I will need a demo project to do some investigation

**Comment by Jaeger87** [comment] 2017-10-22 10:38
Same problem for me, this is my package.json:

{
  "name": "OlgiataWebPortalASPNET4",
  "version": "1.0.0",
  "scripts": {},
  "license": "ISC",
  "dependencies": {
    "@angular/common": "~2.2.0",
    "@angular/compiler": "~2.2.0",
    "@angular/core": "~2.2.0",
    "@angular/forms": "~2.2.0",
    "@angular/http": "~2.2.0",
    "@angular/platform-browser": "~2.2.0",
    "@angular/platform-browser-dynamic": "~2.2.0",
    "@angular/router": "~3.0.2",
    "@angular/upgrade": "~2.2.0",
    "angular2-timepicker": "^1.1.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ng2-date-picker": "^2.5.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.4.3",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "typescript": "^2.0.3",
    "typings": "^1.4.0",
    "ng2-bs3-modal": "0.10.4"
  }
}

I'm pretty sure that the problem is related to this, however if you want the repo how can i post to you?

**Comment by YasserMuhammad** [comment] 2017-10-22 12:25
@Jaeger87 i think that u need to upgrade to Angular 4 
it worked for me when i updated my package.json

**Comment by Jaeger87** [comment] 2017-10-23 08:11
It worked even for me! thank you.

**Comment by gauravrajdeo** [comment] 2018-02-10 12:52
`import { AbstractControl, ValidationErrors } from "@angular/forms";


export class UsernameValidators {
    cannotContainSpace(control: AbstractControl) : ValidationErrors | null {
        if ((control.value as string).indexOf(' ') >= 0) {
            return { cannotContainSpace: true };
        }
        return null;
    }
}`

In my custom validator I'm getting this error while working with angular 2
