### ISSUE TITLE
./locale not found issue

### ISSUE THREAD

**Issue by keshav1007** [vlio20/angular-datepicker#230] opened 2017-10-10 15:18 UTC
Since date picker installs moment 2.19.1 there is a known issue with ./locale not found
https://github.com/moment/moment/issues/2979

So how can i avoid this?

Solution is provided for webpacks but i am not using webpack.

**Comment by vlio20** [comment] 2017-10-10 15:21
What type of bundling are you using?

**Comment by keshav1007** [comment] 2017-10-10 15:36
I am using angular-cli. Is that the one you are asking?

**Comment by priyanka3110** [comment] 2017-10-10 17:36
Module not found: Error: Can't resolve './locale' in 'node_modules\ng2-date-picker\node_modules\moment\src\lib\locale' using the ng2-date-picker

**Comment by vlio20** [comment] 2017-10-10 17:52
@keshav1007, angular cli is using webpack behind the scenes. Could you please  post a simple demo project?

**Comment by priyanka3110** [comment] 2017-10-10 18:23
![image](https://user-images.githubusercontent.com/31878411/31403240-33b673fe-ae16-11e7-9f24-d19e2244fb58.png)

**Comment by vlio20** [comment] 2017-10-10 18:25
@priyanka3110, Could you please post a simple demo project?

**Comment by sweeti270789** [comment] 2017-10-10 18:54
https://github.com/sweeti270789/angular-date-picker-demo 

using the ng2-date-picker which throw above error

---Priyanka

**Comment by vlio20** [comment] 2017-10-10 18:57
Please provide a full demo - including the ng2-date-picker module.

**Comment by priyanka3110** [comment] 2017-10-10 18:57
its full demo using the ng2-date-picker-module installed using npm

**Comment by vlio20** [comment] 2017-10-10 18:59
I can't see it in https://github.com/sweeti270789/angular-date-picker-demo/blob/master/package.json (package.json).

Sorry, but it is hard for me to create demos for each issue :)

**Comment by priyanka3110** [comment] 2017-10-10 19:00
Now you can check I forgot to save in package json, sorry,

**Comment by vlio20** [comment] 2017-10-10 19:10
I will. thanks!

**Comment by alvelig** [comment] 2017-10-10 19:57
`npm i -S moment@2.18.1` should help

**Comment by priyanka3110** [comment] 2017-10-11 12:34
After using 2.18.1 the issue is resolved

**Comment by vlio20** [comment] 2017-10-11 13:07
From my understanding, if you want to use a specific locale, you have to add it to your dependencies.

**Comment by echerepanova** [comment] 2017-10-11 17:31
Agreed, locally this can be fixed with a npm install moment@2.18.1. But this issue fails on our CI/CD pipelines due to the way package.json has "^2.17.1" for moment dependency.

Is there any resolution for such scenarios?

**Comment by vlio20** [comment] 2017-10-11 19:17
@echerepanova, sure. You need to add it to your package.json with specific version. (without ^)

**Comment by vlio20** [comment] 2017-10-12 19:01
@priyanka3110 , I cloned your demo project. And didn't get any error :/

**Comment by vlio20** [comment] 2017-10-14 20:32
@priyanka3110, @keshav1007  I really want to solve this before releasing 2.6.0. I would need your help in reproducing this issue. 

I tried using @priyanka3110 demo, but didn't get any error.

Could you please try to reproduce the issue in the demo page of this component? let me know if you need any help or having any question.

**Comment by vlio20** [comment] 2017-10-23 05:07
will close this for now

**Closed by vlio20** 2017-10-23 05:07 UTC
Labels: Investigation, more info needed
