### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError (directive-based)

### ISSUE THREAD

**Issue by ameyer-pivotal** [vlio20/angular-datepicker#159] opened 2017-08-04 03:27 UTC
Out of the box, I'm trying to use the following in a newly-generated angular CLI project.

In `app.component.html`:
```
<input [(ngModel)]="selectedDate" [dpDayPicker]="datePickerConfig"
       theme="dp-material" mode="month">
```

With the following `app.component.ts`:

```
import { Component } from '@angular/core';
import * as moment from 'moment/moment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  selectedDate: moment.Moment | string;

  datePickerConfig = {
    format: 'MM/YYYY'
  };
}
```

And I receive the following console error immediately:
> ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: ''.

I cannot for the life of me figure out what's going on. I've never experienced this with other date pickers, so there must be something going on...

Versions:
```
└─┬ ng2-date-picker@2.2.0 
  └── moment@2.18.1 
```

**Comment by ameyer-pivotal** [comment] 2017-08-04 03:28
Setting the initial value of `selectedDate` to `''` gets around it, but this is not acceptable, as there will definitely be scenarios where I want to have an initial value.

**Comment by ameyer-pivotal** [comment] 2017-08-04 03:51
Update: Doesn't seem to happen when using the non-directive variant:

```
<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig"
                theme="dp-material" mode="month"></dp-date-picker>
```

**Comment by vlio20** [comment] 2017-08-04 07:46
duplicate of #128

**Comment by vlio20** [comment] 2017-08-04 08:17
I can't reproduce your issue, please see the following screenshot: http://prntscr.com/g481h3. 
It will be helpful if you provide a demo repo.

I will close this issue for now, when more info will be provided I will reopen.

Thanks for the contribution

**Comment by ameyer-pivotal** [comment] 2017-08-04 12:49
Ok, here you are:
https://github.com/ameyer-pivotal-external/angular-datepicker-issue-159

Just run `ng serve` after pulling the code and hopefully you'll see it

**Comment by vlio20** [comment] 2017-08-04 20:50
seems to be related to: https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4
still don't know where is the issue because I can reproduce it on the demo. I will keep digging... 
I would also ask you tot try to reproduce it on the demo component which is part of this repo.

**Comment by vlio20** [comment] 2017-08-04 21:01
@ameyer-pivotal, can you please test with master to see if solves your issue?

**Comment by WaterBleu** [comment] 2017-08-04 22:23
@vlio20 have the same issue on ng 4.3.3.
I believe the problem is that the plugin sets the value (constructor) at the wrong life cycle

**Comment by vlio20** [comment] 2017-08-05 20:20
I was able to reproduce it with 4.3.3 as @WaterBleu mentioned. Thanks. Investigating...

**Closed** 2017-08-05 21:14 UTC

**Comment by menehune23** [comment] 2017-08-05 21:19
Thanks for addressing this! What version will it be on? Is there a way I can pull it through npm?

**Comment by vlio20** [comment] 2017-08-05 21:22
I will make a patch version tomorrow. Currently it's only on master.

**Comment by WaterBleu** [comment] 2017-08-08 18:57
problem persists with version 2.3.0

**Comment by vlio20** [comment] 2017-08-08 19:02
I didn't release the fix yet. Would be part of 2.3.1

**Comment by vlio20** [comment] 2017-08-09 11:26
@WaterBleu, @ameyer-pivotal  let me know if you 2.3.1 is fixing your issue

**Comment by ameyer-pivotal** [comment] 2017-08-09 15:25
Works, thanks!

**Comment by vlio20** [comment] 2017-08-09 15:39
A star would be much appreciated
